In [1]:
print("こんにちは")


こんにちは


In [1]:
for i in range(3):
    print("hello")

hello
hello
hello


In [1]:
1/3

0.3333333333333333

# 機械学習をしよう

(1+2*3-4)/5

In [11]:
(1+2*3-4)/5

0.6

## 

In [12]:
2**8

256

In [2]:
1+2+3

6

# a=1
b=7
a/b

# 3+7

In [13]:
1/x=1
y=1/3
x+y

1.3333333333333333

In [14]:
date_1=1/5
date_2=3/5
date_1+date_2

0.8

In [15]:
type(100)

int

In [16]:
type(1.2)

float

In [18]:
type('learning')

str

In [19]:
x=1/3
print(x)
y=2/3
print(y)

0.3333333333333333
0.6666666666666666


In [20]:
print('x= '+ str(x))

x= 0.3333333333333333


In [21]:
print('weight = {0}kg'.format(x))

weight = 0.3333333333333333kg


x=1/3
y=1/7
z=1/4
print('weight:{0}kg,{1}kg,{2}kg'.format(x,y,z))

In [23]:
x=1/3
y=1/7
z=1/4
print('weight:{0}kg,{1}kg,{2}kg'.format(x,y,z))

weight:0.3333333333333333kg,0.14285714285714285kg,0.25kg


In [26]:
print('weight:{0:.2f}kg,{1:.2f}kg,{2:.2f}kg'.format(x,y,z))

weight:0.33kg,0.14kg,0.25kg


In [28]:
x=[1,1,2,3,5]
print(x)

[1, 1, 2, 3, 5]


In [29]:
x[0]

1

In [30]:
x[2]

2

In [31]:
print(type(x))

<class 'list'>


In [32]:
print(type(x[0]))

<class 'int'>


In [33]:
x[1]

1

In [34]:
x[0]

1

In [39]:
s=['SUN', 1,'MON', 2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [41]:
print(type(s[3]))


<class 'int'>


In [42]:
x[4]

5

In [44]:
s=['SUN', 1,'MON', 2]
print(type(s[0]))
print(type(s[1]))
print(type(s[2]))

<class 'str'>
<class 'int'>
<class 'str'>


In [45]:
a=[[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [51]:
x=[1,1,2,3,5]
x[3]=100
print(x)

[1, 1, 2, 100, 5]


In [52]:
x=[1,1,2,3,5]
len(x)

5

In [53]:
y=range(5,10)
print(y[0],y[1],y[2],y[3],y[4])

5 6 7 8 9


In [54]:
print(y)

range(5, 10)


In [55]:
z=list(range(5,10))
print(z)

[5, 6, 7, 8, 9]


In [56]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
a=(1,2,3)
print(a)

(1, 2, 3)


In [60]:
a[2]

3

In [61]:
type(a)

tuple

In [63]:
a= (1)
type(a)

int

In [64]:
a=(1,)
type(a)

tuple

In [71]:
x=9
if x>10:
    print('x is')
    print('     larger than 10.')
else:
        print('x is smaller than 11')

x is smaller than 11


In [72]:
x>10

False

In [73]:
type(x>10)

bool

In [79]:
x=11
if x>10:
    print('x is')
    print('      larger than 10.')
else:
    print('x is smaller than 11')

x is
      larger than 10.


In [81]:
x=15
if 10<=x and x<=20:
    print('x is between 10 and 20.')

x is between 10 and 20.


In [87]:
for i in [1,2,3]:
    print(i)

1
2
3


In [91]:
num = [2,4,6,8,10]
for i in range(len(num)):
    num[i] = num[i] * 2
    print(num)


[4, 4, 6, 8, 10]
[4, 8, 6, 8, 10]
[4, 8, 12, 8, 10]
[4, 8, 12, 16, 10]
[4, 8, 12, 16, 20]


In [92]:
num=[2,4,6,8,10]
for i,n in enumerate(num):
    num[i]= n*2
    print(num)

[4, 4, 6, 8, 10]
[4, 8, 6, 8, 10]
[4, 8, 12, 8, 10]
[4, 8, 12, 16, 10]
[4, 8, 12, 16, 20]


In [93]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [94]:
import numpy as np

In [95]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [96]:
print(x)

[1 2 3]


In [ ]:
1/4

In [ ]:
1/3

In [98]:
y=np .array([4,5,6])
print(x+y)

[5 7 9]


In [49]:
a=[[1,2,3],[4,5,6]]
print(a[0][1])
print(a[1][0])



2
4
